name: live_tracker_client
description: The frontend for the live tracker application.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  js: ^0.7.1
  # UPGRADED: Using a newer version compatible with the latest 'js' package.
  socket_io_client: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^6.0.0

